---
- hosts: all
  become: yes
  tasks:
          - name: install apache2 on ubuntu node
            apt:
                    name: apache2
                    state: absent


          - name: install wget on ubuntu node
            apt:
                    name: wget
                    state: present